<a href="https://colab.research.google.com/github/Shubzzz24/Goeduhub-Datascience-ML/blob/main/Task_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Task 4**
### **Reg Id : GO_STP_13238**
### **Name : Shubham Rohidas Hundare**

**1)Import the numpy package under the name np and Print the numpy version and the configuration**

In [ ]:
import numpy as np
np.__version__

'1.19.5'

**2) Create a null vector of size 10**

In [ ]:
a = np.zeros(10)
print(a)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**3) Create Simple 1-D array and check type and check data types in array**

In [ ]:
a = np.array([10,2,30,40,50])
print(a)
print(type(a))
print(a.dtype)

[10  2 30 40 50]
<class 'numpy.ndarray'>
int64


**4) How to find number of dimensions, bytes per element and bytes of memory used?**

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print("Dimension ",a.ndim)
print("Size ",a.size)
print("bytes ",a.itemsize)
print("Memory used ",a.size*a.itemsize)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension  2
Size  9
bytes  8
Memory used  72


**5) Create a null vector of size 10 but the fifth value which is 1**

In [ ]:
n = np.zeros(10)
n[5]=1
print(n)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


**6) Create a vector with values ranging from 10 to 49**

In [ ]:
a = np.arange(10,49)
print(a)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


**7) Reverse a vector (first element becomes last)**

In [ ]:
b = np.arange(1,10)
print("Given Array ",b)
print("Reversed array ",b[::-1])

Given Array  [1 2 3 4 5 6 7 8 9]
Reversed array  [9 8 7 6 5 4 3 2 1]


**8) Create a 3x3 matrix with values ranging from 0 to 8**

In [ ]:
c = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**9) Find indices of non-zero elements from [1,2,0,0,4,0]**

In [ ]:
d = np.array([1,2,0,0,4,0])

print(np.nonzero(d))

(array([0, 1, 4]),)


**10) Create a 3x3 identity matrix**

In [ ]:
e = np.identity(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**11) Create a 3x3x3 array with random values**

In [ ]:
f = np.random.random((3,3,3))
print(f)

[[[0.28417128 0.91985439 0.17237441]
  [0.99829568 0.17129342 0.53201083]
  [0.35868922 0.34059025 0.07458405]]

 [[0.01118914 0.16233975 0.82718226]
  [0.27075189 0.27544081 0.01541877]
  [0.8473428  0.30587935 0.7227743 ]]

 [[0.84095011 0.5623952  0.2035345 ]
  [0.56794578 0.62438653 0.18374062]
  [0.92139987 0.20877262 0.65840479]]]


**12)Create a 10x10 array with random values and find the minimum and maximum values**

In [ ]:
g = np.random.random((3,3,3))
print(g)
print("Maximum :",np.max(g))
print("Minimum :",np.min(g))

[[[0.19077278 0.27649658 0.76226178]
  [0.68677134 0.73103017 0.22184727]
  [0.87702799 0.36893623 0.59313451]]

 [[0.6707883  0.55847495 0.6412658 ]
  [0.83473759 0.92483021 0.18588303]
  [0.30010775 0.59234004 0.38255892]]

 [[0.4800813  0.47053166 0.93145158]
  [0.38308172 0.57068918 0.87530499]
  [0.65048027 0.372843   0.99300724]]]
Maximum : 0.9930072398721594
Minimum : 0.1858830327719161


**13) Create a random vector of size 30 and find the mean value**

In [ ]:
h = np.random.random(30)
print(np.mean(h))

0.5214810283991702


**14) Create a 2d array with 1 on the border and 0 inside**

In [ ]:
i = np.ones((4,4))
print(i)
i[1:-1,1:-1]=0
print("\n")
print(i)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


**15) How to add a border (filled with 0's) around an existing array?**

In [ ]:
print("Before :")
j = np.zeros((2,2))
print(j)
print("After :")
j=np.pad(j, pad_width=1, constant_values = 1)
print(j)

Before :
[[0. 0.]
 [0. 0.]]
After :
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


**16) How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?**

Example -
[[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]

Get 13, get first row only, get 3rd column only, get [2, 4, 6], replace 13 by 20

In [ ]:
k = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(k)
print(k[1,5])
print(k[:,2:-4])
print(k[:2:,:])

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
13
[[ 3]
 [10]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


**17) How to Convert a 1D array to a 2D array with 2 rows**

In [ ]:
l = np.array([1,2,3,4,5,6])
print("One Dimensional Array :")
print(l)
print("Two Dimensional Array :")
l.resize(2,3)
print(l)

One Dimensional Array :
[1 2 3 4 5 6]
Two Dimensional Array :
[[1 2 3]
 [4 5 6]]


**18) Create the following pattern without hardcoding. Use only numpy functions and the below input array a.**

Input:

a = np.array([1,2,3])`

Desired Output:

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
m = np.array([1,2,3])
print(m)

m = np.append(np.repeat(m,3),np.tile(m,3))
print(m)

[1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


**19) Write a program to show how Numpy taking less memory compared to Python List?**

In [ ]:
import sys
list1 = range(100)
print("Size of each element is :",sys.getsizeof(list1))
print("Whole size of list is :", sys.getsizeof(list1)*len(list1))

list2 = np.arange(1000)
print("Size of each element is :",list2.itemsize)
print("Whole size of list is :", list2.itemsize*list2.size)

Size of each element is : 48
Whole size of list is : 4800
Size of each element is : 8
Whole size of list is : 8000


**20) Write a program to show how Numpy taking less time compared to Python List?**

In [ ]:
import time

size = 1000000

list1 = range(size)
list2 = range(size)
array1 = np.arange(size)
array2 = np.arange(size)

#list
initial_time = time.time()
res1 = [(a*b) for a,b in zip(list1,list2)]
print("Time taken for multiplication : ",(time.time()-initial_time))

#numpy
initial_time = time.time()
res2 = array1*array2
print("Time taken for multiplication :",(time.time()-initial_time))

Time taken for multiplication :  0.15459513664245605
Time taken for multiplication : 0.0029931068420410156
